version: "3.8"

services:
  postgresql:
    image: postgres:${POSTGRESQL_VERSION}
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - INIT_USER
      - INIT_PASSWORD
      - INIT_DB
      - INIT_PATH
      - TZ
    volumes:
      - type: bind
        source: ../configs/postgresql/docker-entrypoint-initdb.d/
        target: /docker-entrypoint-initdb.d/
        read_only: true
      - type: bind
        source: ../configs/postgresql/init-database/
        target: /init-database/
        read_only: true
      - ../database/postgresql/data/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - elk
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"
      - "-c"
      - "timezone=${TZ}"
      - "-c"
      - "log_timezone=${TZ}"
    restart: always

  elasticsearch:
    build:
      context: ../
      dockerfile: ./build/package/elasticsearch.Dockerfile
      args:
        - ELK_VERSION
    environment:
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - ELASTIC_PASSWORD=changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: bind
        source: ../configs/elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk
    restart: always

  logstash:
    build:
      context: ../
      dockerfile: ./build/package/logstash.Dockerfile
      args:
        - ELK_VERSION
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
    volumes:
      - type: bind
        source: ../configs/logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ../configs/logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    networks:
      - elk
    depends_on:
      - elasticsearch
      - postgresql
    restart: always

  kibana:
    build:
      context: ../
      dockerfile: ./build/package/kibana.Dockerfile
      args:
        - ELK_VERSION
    volumes:
      - type: bind
        source: ../configs/kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: always

  server:
    build:
      context: ../
      dockerfile: ./build/package/server.Dockerfile
      args:
        - GO_VERSION
    environment:
      - TZ
    volumes:
      - ..:/go/src/app
    ports:
      - "8000:8000"
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: always

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
