#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<-EOSQL
    CREATE USER ${INIT_USER} WITH LOGIN PASSWORD '${INIT_PASSWORD}';
    CREATE DATABASE ${INIT_DB} OWNER '${INIT_USER}' ENCODING 'UTF8' LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0;
EOSQL

psql ${INIT_DB} < ${INIT_PATH}
